### ISSUE TITLE
시각화 관련 grafana 차트 설정 미리 하고 사용법 정리

### ISSUE THREAD

**Issue by srlee056** [zizzic/airflow_repo#31]
## TODO
- [x] 사용할 차트 목록 작성
- [x] redshift plugin > cache 부분 설정에 대해 더 알아볼 것
- [x] variable in grafana 정리
    - https://grafana.com/docs/grafana/latest/dashboards/variables/
    - https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/
    - https://play.grafana.org/d/testdata-datalinks/datalinks-variables?orgId=1
 
## 차트 목록
1. sunburt 형태 / 분류 4단계까지 가능
   - https://echarts.apache.org/examples/en/editor.html?c=sunburst-book
   - https://echarts.apache.org/examples/en/editor.html?c=sunburst-drink
2. 데이터셋 연동(?)
   - https://echarts.apache.org/examples/en/editor.html?c=dataset-link
   - https://echarts.volkovlabs.io/d/tg6gWiKVk/line?orgId=1&from=1707188560603&to=1707210160603&viewPanel=40
4. https://echarts.apache.org/examples/en/editor.html?c=line-aqi
5. https://echarts.apache.org/examples/en/editor.html?c=scatter-polar-punchCard
6. morphing
   - https://echarts.apache.org/examples/en/editor.html?c=map-bar-morph
   - https://echarts.apache.org/examples/en/editor.html?c=treemap-sunburst-transition
7. 그래프
  - 한번에 한 분류만 선택 가능한 그래프 : https://echarts.volkovlabs.io/d/oKc5di54k/graph?orgId=1&from=1707188717483&to=1707210317484&viewPanel=12
8. 마우스 이벤트
   - 오버레이 시 라벨 나타남 : https://echarts.volkovlabs.io/d/0b5-q7K4k/pie?orgId=1&from=1707188844468&to=1707210444468&viewPanel=2
   - 트리맵 클릭 시 inside nested tree map을 새로 렌더링 : https://echarts.volkovlabs.io/d/FlnnZ4F4k/treemap?orgId=1&from=1707189104143&to=1707210704144&viewPanel=5
